### PR TITLE
escape pwd for pathname contaning spaces

### LINKED ISSUE #257: post install fail with spaces in pathname
the [postinstall](https://github.com/dwyl/goodparts/blob/2c0bd555294d826cb886c6465fb045c565336405/package.json#L11) command fails if the path name represented by $(pwd) contains spaces

### PR DESCRIPTION
**Pull request by SimonLab**
- resolve #257 by adding double quotes around $(pwd)
- resolve new rule in #256 func-name-matching

### CODE REVIEW

File: rules/stylistic_issues.js [hunk 1]
```diff
@@ -118,5 +118,6 @@ module.exports = {
     beforeColon: false, afterColon: true, mode: 'strict'
   }], // https://github.com/dwyl/goodparts/issues/198
   'no-restricted-syntax': 0, // https://github.com/dwyl/goodparts/issues/111
-  'no-continue': 2 // https://github.com/dwyl/goodparts/issues/162
+  'no-continue': 2, // https://github.com/dwyl/goodparts/issues/162,
+  'func-name-matching': 2 // https://github.com/dwyl/goodparts/issues/256
```
Comment (nelsonic) [inline rules/stylistic_issues.js]: this new rule is not _strictly_ necessary. but I don't have any issue with including it. 😉

**Comment by nelsonic** [comment]
@SimonLab looks good. thanks for fixing that! 👍
