### PR TITLE
test elias rules

### LINKED ISSUE #17: wrap-regex
https://eslint.org/rules/wrap-regex

[JSLint](http://jslint.com/help.html) says the following: 
> JavaScript's syntax for regular expression literals overloads the / slash character. To avoid ambiguity, JSLint expects that the character preceding a regular expression literal is a ( left paren or = equal or : colon or , comma character.

But this rule is meant to avoid the regular expression looking like a division operator, but this will never be the case.

This rule is therefore turned off.

```
wrap-regex: "off"
```

### LINKED ISSUE #20: spaced-comment
http://eslint.org/docs/rules/spaced-comment

Choose "always" to improve legibility

```
"spaced-comment": [2, "always"]
```

### LINKED ISSUE #32: space-infix-ops
http://eslint.org/docs/rules/space-infix-ops

`2, {"int32Hint": false}]`

readability reasons but allowing for `bar|0`

### LINKED ISSUE #34: space-in-parens
http://eslint.org/docs/rules/space-in-parens

Spaces in parens are unnecessary here and do not add to legibility.

```
"space-in-parens": [2, "never"]
```

### LINKED ISSUE #38: sort-vars
http://eslint.org/docs/rules/sort-vars

Alphabetical ordering is arbitrary: there is usually a more natural ordering in a given context.

```
"sort-vars": "off"
```

### LINKED ISSUE #39: sort-keys
http://eslint.org/docs/rules/sort-keys

See, #38: allow for a more natural ordering of keys

```
"sort-keys": "off"
```

### LINKED ISSUE #50: semi-spacing
http://eslint.org/docs/rules/semi-spacing

Enforcing no space before, but a space afterward is consistent with normal english syntax

```
"semi-spacing": ["error", {"before": false, "after": true}]
```

### LINKED ISSUE #53: quotes
http://eslint.org/docs/rules/quotes

Single quotes because:
* no shift key required
* easier to context switch between JS and HTML (as long as you use double quotes in your HTML)

Do not allow template literals because they are an ES6 feature.
Prefer use of escape characters instead of having inconsistent quoting style.

```
"quotes": [2, "single", {"avoidEscape": false, "allowTemplateLiterals": false}]
```

### LINKED ISSUE #54: quote-props
http://eslint.org/docs/rules/quote-props

Choose "consistent-as-needed" because:
* Prefer to drop unnecessary characters
* But prefer consistency within an object declaration over brevity
* Keywords should be quoted to avoid ambiguity

```
[2, "consistent-as-needed", { "keywords": false }]
```

### LINKED ISSUE #55: padded-blocks
http://eslint.org/docs/rules/padded-blocks

Disallow padding blocks, blocks are already demarcated by curly braces

```
[2, "never"]
```

### LINKED ISSUE #112: callback-return
http://eslint.org/docs/rules/callback-return

Should definitely return callbacks, but this rule only looks at predefined function names, so does not offer full protection. 

Would be worth deciding on a convention for callback names, and adding those to the list of calback names

```
["error", ["done", "next", "callback", "cb"]]
```

### LINKED ISSUE #119: global-require
http://eslint.org/docs/rules/global-require

Calls to require should be in top-level scope and preferably at the top of the file to make all the dependencies of a module explicit

```
"error"
```

### LINKED ISSUE #121: handle-callback-err
http://eslint.org/docs/rules/handle-callback-err

In principle, we should be using the node convention of passing the error as the first argument. Much like #112, however, this rule is enforced by checking for predefined names of error arguments.

Can define a regex to look for arguments considered to represent errors.

```
handle-callback-err: ["error", "^(error|err\d*)$"]
```

### LINKED ISSUE #126: no-mixed-requires
http://eslint.org/docs/rules/no-mixed-requires

Expect calls to require to be grouped by category to make it clear which modules are core, which are third party, etc.

Disallow calls on the same line as requires because they should just be a declaration of dependencies rather than part of the modules logic.

```
["error", { "grouping": true, "allowCall": false }]
```

### LINKED ISSUE #129: no-new-require
http://eslint.org/docs/rules/no-new-require

Like in #126, the requires should be a declaration of dependencies, not part of the logic of the module.

```
no-new-require: "error"
```

### LINKED ISSUE #132: no-path-concat
http://eslint.org/docs/rules/no-path-concat

Always use the path module when constructing filepaths for portability

```
no-path-concat: "error"
```

### LINKED ISSUE #134: no-process-env
http://eslint.org/docs/rules/no-process-env

Environment variables are used to pass info about deployment environment to the js, and also used to store secrets, so keeping this rule off.

```
no-process-env: "off"
```

### LINKED ISSUE #136: no-process-exit
http://eslint.org/docs/rules/no-process-exit

Should have a better exception handling strategy

```
no-process-exit: "error"
```

### LINKED ISSUE #139: no-restricted-modules
http://eslint.org/docs/rules/no-restricted-modules

Can be used to restrict dangerous modules. Dont use this unless there is a module we want to avoid.

```
no-restricted-modules: "off"
```

### LINKED ISSUE #143: no-restricted-properties
http://eslint.org/docs/rules/no-restricted-properties

Dont restrict props unless there is a good reason

```
no-restricted-properties: "off"
```

### LINKED ISSUE #144: no-sync
http://eslint.org/docs/rules/no-sync

There are contexts where sync operations are acceptable and reduce indentation, e.g. in tests or while performing server setup.

```
no-sync: "off"
```

### LINKED ISSUE #150: no-shadow-restricted-names
http://eslint.org/docs/rules/no-shadow-restricted-names

```
no-shadow-restricted-names: "error"
```

### LINKED ISSUE #151: no-undef-init
http://eslint.org/docs/rules/no-undef-init

avoid redundant code

```
no-undef-init: "error"
```

### LINKED ISSUE #152: no-undefined
http://eslint.org/docs/rules/no-undefined

avoid problems with shadowing undefined

no-undefined: "error"

### LINKED ISSUE #153: no-use-before-define
http://eslint.org/docs/rules/no-use-before-define

code is more readable if definitions precede usage

no-use-before-define: "error"

### LINKED ISSUE #186: max-len
http://eslint.org/docs/rules/max-len

`["error", {
    code: 80,
    ignoreTrailingComments: true,
    comments: 80,
    tabWidth: 2,
    ignoreUrls: false,
    ignoreStrings: false,
    ignoreTemplateLiterals: false
  }]`

why [80](http://programmers.stackexchange.com/questions/148677/why-is-80-characters-the-standard-limit-for-code-width)

### LINKED ISSUE #199: jsx-quotes
eslint.org/docs/rules/jsx-quotes

```
jsx-quotes: "off"
```

jsx isnt part of the [standard dwyl stack](https://github.com/dwyl/technology-stack), so this is N/A

### LINKED ISSUE #201: indent
http://eslint.org/docs/rules/indent

```
"indent": ["error", 2]
```

4-space indent is reccommended by goodparts http://jslint.com/help.html but going with 2

### LINKED ISSUE #202: id-match
http://eslint.org/docs/rules/id-match

```
"id-match": "off"
```

Not sure, so not imposing this right now. Could use it to enforce for example camel case variable names, but this should be discussed first.

### LINKED ISSUE #204: id-length
http://eslint.org/docs/rules/id-length

```
id-length: "off"
```

more descriptive variable names are better, but dont want to restrict conciseness for well understood conventions like loop variables (`i`, `ii`), or unused variables (`_`)

### LINKED ISSUE #205: id-blacklist
http://eslint.org/docs/rules/id-blacklist

```
"id-blacklist": "off"
```

Happy to add things to a blacklist if there's a good case for it.

### LINKED ISSUE #207: func-style
http://eslint.org/docs/rules/func-style

```
func-style: "off"
```

Allow both styles cf. JSLint

### LINKED ISSUE #208: func-names
http://eslint.org/docs/rules/func-names

```
func-names: "off"
```

allow unnamed functions in expressions

### LINKED ISSUE #209: func-call-spacing
http://eslint.org/docs/rules/func-call-spacing

```
func-call-spacing: ["error", "never"]
```

### LINKED ISSUE #210: eol-last
http://eslint.org/docs/rules/eol-last

```
eol-last: "error"
```

Common UNIX idiom

### LINKED ISSUE #211: consistent-this
http://eslint.org/docs/rules/consistent-this

```
consistent-this: "off"
```

Shouldn't be relying on `this` if at all possible, so largely N/A

### LINKED ISSUE #212: computed-property-spacing
http://eslint.org/docs/rules/computed-property-spacing

```
computed-property-spacing: ["error", "never"]
```

Doesn't help legibility much

### LINKED ISSUE #213: comma-dangle
http://eslint.org/docs/rules/comma-dangle

```
comma-dangle: ["error", "never"]
```

JSLint says:
> A comma should not appear after the last element of an array literal or object literal.

### LINKED ISSUE #214: comma-spacing
http://eslint.org/docs/rules/comma-spacing

```
comma-spacing: ["error", { "before": false, "after": true }]
```

### LINKED ISSUE #215: comma-style
http://eslint.org/docs/rules/comma-style

```
comma-style: ["error", "last"]
```

### LINKED ISSUE #216: camelcase
http://eslint.org/docs/rules/camelcase

```
camelcase: "error"
```

Prefer consistent naming convention, camel case is more idiomatic of javascript.

### LINKED ISSUE #217: brace-style
http://eslint.org/docs/rules/brace-style

```
["error", "1tbs", { "allowSingleLine": true }]
```

Use 1tbs by default, allow single line statements, although should only use them in v. simple cases

### LINKED ISSUE #218: block-spacing
http://eslint.org/docs/rules/block-spacing

```
block-spacing: "error"
```

Enforce spacing in single line statements for readability.

### LINKED ISSUE #219: array-bracket-spacing
http://eslint.org/docs/rules/array-bracket-spacing

```
["error", "never"]
```

No array spacing

### PR DESCRIPTION
**Pull request by SimonLab**
Ready for review!
related to:
Resolves #219 
Resolves #218 
Resolves #217 
Resolves #216 
Resolves #215 
Resolves #214 
Resolves #213 
Resolves #212 
Resolves #211 
Resolves #210 
Resolves #209 
Resolves #208 
Resolves #207 
Resolves #205 
Resolves #204 
Resolves #202 
Resolves #201 
Resolves #199 
Resolves #186 
Resolves #153 
Resolves #152 
Resolves #151 
Resolves #150
Resolves #144 
Resolves #143 
Resolves #139 
Resolves #136 
Resolves #134 
Resolves #132 
Resolves #129 
Resolves #126 
Resolves #121 
Resolves #119 
Resolves #112 
Resolves #55 
Resolves #54 
Resolves #53 
Resolves #50 
Resolves #39 
Resolves #38 
Resolves #34 
Resolves #32 
Resolves #20 
Resolves #17

### CODE REVIEW

**Comment by jrans** [comment]
@SimonLab Can you reference the issues that this PR resolves? so once merged will close them all.

File: rules/stylistic_issues.js [hunk 1]
```diff
@@ -1,5 +1,33 @@
 module.exports = {
   "space-infix-ops": ["error", {"int32Hint": false}], // https://github.com/dwyl/goodparts/issues/32
+  "max-len": ["error", 80], // https://github.com/dwyl/goodparts/issues/186
```
Comment (jrans) [inline rules/stylistic_issues.js]: duplicate max-len

Comment (jrans) [inline rules/stylistic_issues.js]: remove this one as other is more exact
