### PR TITLE
Fixing tests

### LINKED ISSUE #66: no-caller
http://eslint.org/docs/rules/no-caller

```
no-caller: 2
```

using arguments.caller and arguments.callee add complexity and confusion we shouldn't use them

### LINKED ISSUE #75: no-eq-null
http://eslint.org/docs/rules/no-eq-null

```
no-eq-null: 2
```

This rule doesn't allow to to check null values without the type-checking:

bad: 

````
val == null
```

good:

```
val === null
```

However this rule won't applied if we decide to not use null but only undefined

### LINKED ISSUE #108: no-throw-literal
http://eslint.org/docs/rules/no-throw-literal

Do we want to only throw Error objects?

#### Update
```
no-throw-literal: "error"
```

### LINKED ISSUE #124: wrap-iife
http://eslint.org/docs/rules/wrap-iife

### LINKED ISSUE #128: strict
http://eslint.org/docs/rules/strict

```
strict: 2
```
I'm not sure about this rule, I think it can add more checks and good practice by using it but we also have all the other eslint which let us know if something is wrong

### LINKED ISSUE #135: init-declarations
http://eslint.org/docs/rules/init-declarations

I don't think we should impose this rule at the moment, I tend to initialise variables when they are declared but also later on during the code

### LINKED ISSUE #138: no-catch-shadow
http://eslint.org/docs/rules/no-catch-shadow

```
no-catch-shadow: 2
```

This rule add more consistency in the code and help us to avoid IE8 bug

### LINKED ISSUE #140: no-delete-var
http://eslint.org/docs/rules/no-delete-var

```
no-delete-var: 2
```
Don't use delete on variables

### LINKED ISSUE #141: no-label-var
http://eslint.org/docs/rules/no-label-var

```
no-label-var: 2
```
Don't create label with the same name as a variable which is on the same scope

### LINKED ISSUE #154: no-restricted-globals
http://eslint.org/docs/rules/no-restricted-globals

It's unlikely that we name variable with the same name as a global variable but we can still use this rule if we need to.

### LINKED ISSUE #156: no-shadow
http://eslint.org/docs/rules/no-shadow

```
no-shadow: 2
```
This rule help to not confuse multiple variable with same names

### LINKED ISSUE #157: no-undef
http://eslint.org/docs/rules/no-undef

```
no-undef: 2
```
help to avoid typo or creating global variable by error

### LINKED ISSUE #158: no-unused-vars
http://eslint.org/docs/rules/no-unused-vars

```
no-unused-vars: 2
```
no unused variables!

### LINKED ISSUE #237: There are some failing tests
Because of:

Forgetting a config option,
Config option mistakes,
a mistake in the tests,
or forgetting to test a config option

As of #236 we have 28 failing tests

### LINKED ISSUE #238: Test if there are syntax errors in our `.eslintrc` file
Pr #235 fixed a syntax error in our `.eslintrc`, we currently do not have a test to detect if there are syntax errors e.g.

```
Configuration for rule "no-constant-condition" is invalid
```

The test needs to do the equivalent of running `npm run lint` and verifying that there were no syntax errors.

### LINKED ISSUE #239: no-unsafe-negation
http://eslint.org/docs/rules/no-unsafe-negation

```
"no-unsafe-negation": "error"
```

If this is done intentionally, I think the code it produces is not beginner friendly.

### LINKED ISSUE #240: no-unreachable
http://eslint.org/docs/rules/no-unreachable

```
no-unreachable: "error"
```

No reason to have dead code.

### LINKED ISSUE #241: no-template-curly-in-string
http://eslint.org/docs/rules/no-template-curly-in-string

```
"no-template-curly-in-string": "off"
```

Setting off for now because, by eslints own advice:
> This rule should not be used in ES3/5 environments.

Also could cause problems with some template engines in older versions of node (h/t @tunnckoCore)

### LINKED ISSUE #242: no-regex-spaces
Multiple spaces in regex are unnecessary

```
no-regex-spaces: "error"
```

### PR DESCRIPTION
**Pull request by shouston3**
We have no more failing tests!

Fixes #238 
Fixes #237
Fixes #239 
Fixes #240 
Fixes #241 
Fixes #242 
Fixes #158 
Fixes #157
Fixes #156 
Fixes #154 
Fixes #141 
Fixes #140 
Fixes #138 
Fixes #135 
Fixes #128 
Fixes #124 
Fixes #108 
Fixes #75 
Fixes #66

### CODE REVIEW

**Comment by nelsonic** [comment]
@shouston3 this is looking promising! 👍 
(_also, don't bother with Node.js v4 in the `travis.yml` file ... v6 will be LTS from next week_! [2016-10-01](https://github.com/nodejs/LTS) 😉 )

File: rules/es6.js [hunk 1]
```diff
@@ -0,0 +1,33 @@
+module.exports = {
```
Comment (nelsonic) [inline rules/es6.js]: @shouston3 _thanks_ for adding this file. 
It would be good to create _issues_ as the ES6 features get requested/discussed. 👍 
(_so for now, this is perfect_)

File: rules/stylistic_issues.js [hunk 2]
```diff
@@ -90,5 +87,7 @@ module.exports = {
   "linebreak-style": ["error", "unix"], // https://github.com/dwyl/goodparts/issues/195
   "line-comment-position": "error", // https://github.com/dwyl/goodparts/issues/196
   "keyword-spacing": ["error", { "before": true, "after": true }], // https://github.com/dwyl/goodparts/issues/197
-  "key-spacing": ["error", { "beforeColon": false, "afterColon": true, "mode": 'strict' }] // https://github.com/dwyl/goodparts/issues/198
+  "key-spacing": ["error", { "beforeColon": false, "afterColon": true, "mode": 'strict' }], // https://github.com/dwyl/goodparts/issues/198
```
Comment (nelsonic) [inline rules/stylistic_issues.js]: prefer if settings were on _separate_ lines in the future to simplify tracking the diff when it gets updated...
(_but OK for now..._)

**Comment by nelsonic** [comment]
@shouston3 & @eliascodes great work! thanks! 
dance
